#166272295 Create User Signup
andela/kingsmen-ah-frontend pull request #17
Opened 2019-07-12 18:52 UTC by emmygozi

#### What does this PR do?
Creates User Signup

#### Description of Task to be completed?
- User can signup on application

#### How should this be manually tested?
`git clone https://github.com/andela/kingsmen-ah-frontend.git`
`git pull 166272295-ft-create-user-signup`
`npm run start:dev`
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/166272295

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/32358797/61151750-9457fc80-a4de-11e9-836f-0e19857346f3.png)

#### Questions:
N/A

2019-07-23 11:02 UTC, EMacco requested changes

2019-07-23 11:02 UTC, EMacco commented on package.json
> +    "joi-browser": "^13.4.0",
Signup works fine, although you could consider removing unused packages

2019-07-23 15:59 UTC, EMacco approved these changes
This looks good

2019-07-23 16:01 UTC, EMacco requested changes
Great work. You might want to work on your test. It is currently failing.

2019-07-23 16:08 UTC, EMacco approved these changes

2019-07-30 06:27 UTC, GerrardE approved these changes
This good

2019-07-30 10:54 UTC, merged