#166272290 Setup End to End Testing
andela/kingsmen-ah-frontend pull request #9
Opened 2019-07-06 15:39 UTC by GerrardE

#### What does this PR do?
Set up end to end testing for the application

#### Description of Task to be completed?
- Install and configure cypress for end to end testing
- Write sample tests

#### How should this be manually tested?
1. clone this repo
2. run "npm install"
3. run "npm run cypress:all" or "npm run cypress:open" 

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166272290](https://www.pivotaltracker.com/story/show/166272290)

#### Screenshots (if appropriate)
<img width="1196" alt="Screenshot 2019-07-05 at 7 22 11 PM" src="https://user-images.githubusercontent.com/22410701/60758220-a6342e00-a00c-11e9-885b-2f2ce9706d24.png">

#### Questions:
N/A

2019-07-07 17:07 UTC, despeauxz submitted a review, later dismissed

2019-07-07 19:25 UTC, EMacco submitted a review, later dismissed
Great job. Tests work fine.

2019-07-07 20:32 UTC, despeauxz submitted a review, later dismissed

2019-07-07 22:07 UTC, fidelisojeah requested changes

2019-07-07 22:07 UTC, fidelisojeah commented on .circleci/config.yml
> +      - image: cypress/base:8
lol what are you even doing?

please create a new job and move your tests there

2019-07-08 11:27 UTC, GerrardE commented on .circleci/config.yml
> +      - image: cypress/base:8
I have implemented this feedback, Thanks

2019-07-09 14:11 UTC, despeauxz approved these changes

2019-07-09 14:58 UTC, adex001 approved these changes
Looks good and works well.

2019-07-09 22:16 UTC, fidelisojeah approved these changes

2019-07-09 22:17 UTC, merged